SIZE_X = 800
SIZE_Y = 600
player_ship = "textures\\ships\\player_ship.png"
background = "textures\\background\\space_bkg_2.jpg"
ufo_one = "textures\\ships\\ufo.png"
missile = "textures\\ships\\missile.png"
player_fire_delay = 100
enemy_spawn_rate = 1000
explosions = "textures\\expl.png"
icon = "textures\\icon.png"
font = 'Comic Sans MS'
